### ISSUE TITLE
Consider including blint

### ISSUE THREAD

**Issue by prabhu** [packing-box/awesome-executable-packing#1]
Excellent list!

Could you kindly consider my linting tool called blint?

https://pypi.org/project/blint/

An example workflow where blint is used to identify potential malware from abuse.ch feed

https://github.com/ngcloudsec/blint-bin/runs/4497789454?check_suite_focus=true

**Comment by dhondta** [comment]
Hi @prabhu 
Thank you for proposing your tool !
However, this list is only related to researches about executable packing.
I think your tool should definitely be published on another awesome list, [awesome-malware-analysis](https://github.com/rshipp/awesome-malware-analysis), as it is a tool that is more useful in the context of malware analysis.
