### ISSUE TITLE
I have archives of old websites related to this.

### ISSUE THREAD

**Issue by devilsclaw** [packing-box/awesome-executable-packing#2]
One of the site's I have a archived is the old CrackPL Tools. This site has old packers and unpacker tools and tutorials.

The other site is `www.mesa-sys.com` which is an old crackme's website not sure if its useful to you,

**Comment by dhondta** [comment]
Could you tell more about CrackPL tools ? Can you provide a link ?

**Comment by dhondta** [comment]
Moreover, mesa-sys.com seems to be for sale. Could you tell more about the site you mentioned ?

**Comment by devilsclaw** [comment]
The sites no longer exist. I archived them back in the day, just in case they ever shut down.

I originally tried a google drive but it flagged the files. due to the nature of that type of site its bound to happen. I would still be careful with the files but it is real backups of those sites. here are the links to the files from my site.

http://www.devilsclaws.net/downloads/other/CrackPL_Tools.zip
http://www.devilsclaws.net/downloads/other/www.mesa-sys.com.zip

The sites were dedicated to reverse engineering. the crackme which was the mesa website was a site with a collection of small programs made by the community with protections to break.

**Comment by dhondta** [comment]
PR ?... 😁

**Comment by devilsclaw** [comment]
Sorry not sure what PR stands for in this instance.

**Comment by dhondta** [comment]
I mean this is worth a Pull Request. Simply edit the README.md (respecting the contributing guidelines, of course) with your new ideas. You can reference the links to your own site as the original ones are broken.
