### ISSUE TITLE
Advice?

### ISSUE THREAD

**Issue by kovalensky** [packing-box/awesome-executable-packing#5]
Hello, sorry for posting something like this question.

Since the list is big, I thought to address it to people who know.

I have a specifically compiled php interpreter exe file with its libraries, I'm seeking for solution which will extract them to temporary folder (if they're not already exist) and run this executable with arguments to open script and return its result to command window from which it was called.
Boxedapp is slow and has inefficient compressing.
All of php packers either huge in output size, or deprecated, in any case I want universal packer.
Something like Enigma Virtual Box, but faster and less in build size, 7z compressed exe weighs 1.5mb, but after adding this to Enigma, it increases to 3mb due to enigmas additional binaries, so something like sfx extractor, but with ability to return results, not start another window. Thanks.

**Comment by loneicewolf** [comment]
@kovalensky  is this still relevant? Just asking to be sure 
wishes from sweden!

**Comment by kovalensky** [comment]
> @kovalensky is this still relevant? Just asking to be sure wishes from sweden!

Yes, it still is :)

**Comment by loneicewolf** [comment]
> > @kovalensky is this still relevant? Just asking to be sure wishes from sweden!
> 
> Yes, it still is :)

👍🏼 Okay, thanks for replying!

**Comment by loneicewolf** [comment]
> > @kovalensky is this still relevant? Just asking to be sure wishes from sweden!
> 
> Yes, it still is :)

Can you share it?

**Comment by kovalensky** [comment]
> Can you share it?

@loneicewolf Share what?

**Comment by loneicewolf** [comment]
> > Can you share it?
> 
> @loneicewolf Share what?

The - 'compiled php interpreter exe file with its libraries' - you talk about. Or are your question more 'generally speaking'? 
Sorry, I'm just a bit confused :)

**Comment by kovalensky** [comment]
@loneicewolf I want to find a packer which will unpack files at given location in first install and called main exe file which will return result to command line window (STDOUT).

If files exist they won't we overwritten only reused.

**Comment by loneicewolf** [comment]
> @loneicewolf I want to find a packer which will unpack files at given location in first install and called main exe file which will return result to command line window (STDOUT).
> 
> If files exist they won't we overwritten only reused.

Oh okay, I misunderstood (this reply is to show I read your reply)

**Comment by kovalensky** [comment]
@dhondta Actually it was not resolved yet :D

**Comment by dhondta** [comment]
@kovalensky Sorry but I think this question has nothing to do here. Please ask on reddit.com or a similar forum.

**Comment by kovalensky** [comment]
Well I dumped reddit for Lemmy, but yeah, I asked that there before, no answers :/
